### ISSUE TITLE
Is Console grid search down?

### ISSUE THREAD

**Issue by iantpryor** [scottrice/ConsoleGrid#34] opened 2015-12-12 15:22 UTC
Can't pull images using ice, can't search on consolegrid.com -  "We're sorry, something wen't wrong." error.  

Can still go to individual game pages, ie http://consolegrid.com/games/438 still shows the Metroid game page.

**Comment by TypeDan** [comment] 2015-12-14 16:19
I'm getting the same thing, Ian :(

**Comment by CubeFusion** [comment] 2015-12-15 03:22
This is likely a duplicate of issue #16 
Apparently the Apache Solr application powering the sites search is crashing, and has to be manually restarted.

**Comment by Hunk4TH** [comment] 2015-12-16 20:27
Same problem here. Hopefully the server can be restarted soon.

**Comment by StormPooper** [comment] 2015-12-21 16:03
Looks like it's still happening, which is preventing Ice from retrieving game images (scottrice/Ice#322).

**Comment by Hunk4TH** [comment] 2015-12-22 06:28
Same problem here...

**Comment by jawshey** [comment] 2015-12-23 18:22
So we're nearing the two week mark now since ConsoleGrid went down - are there any updates? :(

**Comment by scottrice** [comment] 2015-12-31 18:28
I'm aware of the issue, but due to the holidays and some technical problems I'm unable to get a fix out for a couple days. Hoping to restore service soon.

**Comment by jawshey** [comment] 2015-12-31 20:33
Excellent! Wishing a happy new year to you Scott!

**Comment by TypeDan** [comment] 2016-01-01 09:17
Sweet, look forward to it. Happy new year

**Comment by Hunk4TH** [comment] 2016-01-02 06:34
Awesome news Scott happy new year!

**Comment by scottrice** [comment] 2016-01-03 20:59
Alright, ConsoleGrid should be back up. Sorry for the delay, and thanks for the patience. Let me know if you run into any more issues!

**Closed by scottrice** 2016-01-03 20:59 UTC

**Comment by ghost** [comment] 2016-01-04 09:10
Thank you, have a good one

Kind Regards,

Daniel
